### ISSUE TITLE
LLVM IR parsing error crash on unreachable code/early return

### ISSUE THREAD

**Issue by leanderBehr** [Zettelkasten/sleepy#14]
```
func main() {
    return;
    i = 1;
}
```
This crashes the compiler with
```
EXCEPTION
Traceback (most recent call last):
  File "./tools/sleepy.py", line 100, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7fc562c4baf0>
  File "./tools/sleepy.py", line 86, in main
    line: module_ref = llvm.parse_assembly(str(module_ir))
    locals:
      module_ref = <not found>
      llvm = <global> <module 'llvmlite.binding' from '/home/leander/PycharmProjects/sleepy/venv/lib/python3.8/site-packages/llvmlite/binding/__init__.py'>
      llvm.parse_assembly = <global> <function parse_assembly at 0x7fc562c931f0>
      str = <builtin> <class 'str'>
      module_ir = <local> ; ModuleID = "default_module"
                          target triple = "unknown-unknown-unknown"
                          target datalayout = ""
                          
                          define void @"io"() 
                          {
                          entry:
                            ret void
                          }
                          
                          define void @"free_DoubleType"(double %".1") 
                          {
                          entry:
                            ret void
                          }
                          
                          define void @"free_BoolType"(i1 %".1") 
                          {
                          entry:
                            ret void
                          }
                          
                          define void @"free_IntTyp...
  File "/home/leander/PycharmProjects/sleepy/venv/lib/python3.8/site-packages/llvmlite/binding/module.py", line 25, in parse_assembly
    line: raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
    locals:
      RuntimeError = <builtin> <class 'RuntimeError'>
      format = <builtin> <built-in function format>
      errmsg = <local> <llvmlite.binding.ffi.OutputString object at 0x7fc562b10370>
RuntimeError: LLVM IR parsing error
<string>:986:1: error: expected instruction opcode
}
^
```

**Comment by Zettelkasten** [comment]
Fixed this for now by throwing an error. In the future we'll probably want to just raise a warning and skip the rest of the function, but there's no warnings yet
